arenasurf/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    path("", TemplateView.as_view(template_name="homepage.html"), name="home"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("bonos/", include("bonos.urls")),
    path("clientes/", include("clientes.urls")),
    path("socios/", include("socios.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bonos/urls.py
from django.urls import path
from . import views

app_name = 'bonos'

urlpatterns = [
    # Dashboard
    path('', views.dashboard, name='dashboard'),
    
    # Bonos
    path('bonos/', views.BonoListView.as_view(), name='lista'),
    path('bonos/nuevo/', views.BonoCreateView.as_view(), name='crear'),
    path('bonos/<int:pk>/', views.BonoDetailView.as_view(), name='detalle'),
    path('bonos/<int:pk>/editar/', views.BonoUpdateView.as_view(), name='editar'),
    path('bonos/<int:pk>/eliminar/', views.BonoDeleteView.as_view(), name='eliminar'),
    path('bonos/<int:pk>/usar/', views.usar_bono, name='usar'),
    path('bonos/<int:pk>/agregar-uso/', views.agregar_uso_bono, name='agregar_uso'),
]

clientes/urls.py
from django.urls import path
from . import views
from . import panel_views

app_name = 'clientes'

urlpatterns = [
    # URLs para administración (staff)
    path('', views.ClienteListView.as_view(), name='lista'),
    path('nuevo/', views.ClienteCreateView.as_view(), name='crear'),
    path('<int:pk>/', views.ClienteDetailView.as_view(), name='detalle'),
    path('<int:pk>/editar/', views.ClienteUpdateView.as_view(), name='editar'),
    path('<int:pk>/eliminar/', views.ClienteDeleteView.as_view(), name='eliminar'),
    
    # URLs para panel de cliente
    path('registro/', panel_views.ClienteRegistrationView.as_view(), name='registro'),
    path('panel/', panel_views.ClientePanelView.as_view(), name='panel'),
    path('api/perfil/', panel_views.cliente_perfil_ajax, name='perfil_ajax'),
    path('api/bonos/', panel_views.cliente_bonos_ajax, name='bonos_ajax'),
]

socios/urls.py
from django.urls import path
from . import views

app_name = 'socios'

urlpatterns = [
    # Dashboard
    path('', views.dashboard_socios, name='dashboard'),
    
    # Socios CRUD
    path('socios/', views.SocioListView.as_view(), name='lista'),
    path('socios/nuevo/', views.SocioCreateView.as_view(), name='crear'),
    path('socios/<int:pk>/', views.SocioDetailView.as_view(), name='detalle'),
    path('socios/<int:pk>/editar/', views.SocioUpdateView.as_view(), name='editar'),
    path('socios/<int:pk>/eliminar/', views.SocioDeleteView.as_view(), name='eliminar'),
    path('socios/<int:pk>/renovar/', views.renovar_socio, name='renovar'),
]

arenasurf/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="navbar-nav ms-auto">
    {% if request.user.is_authenticated %}
        <li class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

arenasurf/templates/_footer.html
{% load i18n %}

{% now "Y" as current_year %}

{% blocktrans %}
<div class="copyright">&copy; {{ current_year }} &lt;La Arena Surf Center&gt;</div>
{% endblocktrans %}

<div class="made-with-pinax">
    Made with Pinax
    <div class="patches">
        {% for app in pinax_apps %}
            <img src="https://pinaxproject.com/pinax-design/patches/{{ app }}.svg" />
        {% endfor %}
    </div>
</div>

arenasurf/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load static %}

{% block head_title %}La Arena Surf Center{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}Bienvenido a<div style="font-size: 6rem; font-weight: 600;">La Arena Surf Center</div>{% endblocktrans %}</h1>
            <p class="lead">
                {% blocktrans %}
                Más de 400m² dedicados al surf en una zona privilegiada, a solo 100m de la 
                playa de La Arena en Zierbena, Bizkaia. Aprende y desarrolla la práctica 
                del surf en las mejores condiciones con nuestros instructores profesionales.
                {% endblocktrans %}
            </p>
            {% if not user.is_authenticated %}
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p class="mb-5 lead">{% blocktrans %}Puedes <a href="{{ login_url }}" class="btn btn-secondary">Iniciar Sesión</a> o <a href="{{ signup_url }}" class="btn btn-primary">Registrarte</a> para acceder a todos nuestros servicios.{% endblocktrans %}</p>
            {% endif %}
        </div>
    </section>
    <section id="content-section">
        <div id="content-body">
            <h2 class="text-center">{% blocktrans %}¿Por qué elegir La Arena Surf Center?{% endblocktrans %}</h2>
            <p class="lead text-center">
                {% blocktrans %}
                <b>La Arena Surf Center</b> es tu centro de referencia para el surf en el País Vasco.
                Ubicados estratégicamente junto a la playa de La Arena, ofrecemos una experiencia 
                completa para surfistas de todos los niveles.
                {% endblocktrans %}
            </p>

            <div class="feature-columns row">
                <div class="col">
                    <div class="icon"><i class="fas fa-water fa-3x text-primary"></i></div>
                    <div class="desc">
                        <h4>{% blocktrans %}Escuela de Surf{% endblocktrans %}</h4>
                        {% blocktrans %}
                        <b>Cursos para todos los niveles</b> desde principiantes hasta 
                        avanzados. Cursos familiares, campamentos de verano y programas 
                        especiales para centros educativos.
                        {% endblocktrans %}
                    </div>
                </div>
                <div class="col">
                    <div class="icon"><i class="fas fa-warehouse fa-3x text-success"></i></div>
                    <div class="desc">
                        <h4>{% blocktrans %}Instalaciones{% endblocktrans %}</h4>
                        {% blocktrans %}
                        <b>Más de 400m² de instalaciones</b> modernas y completamente 
                        equipadas para el surf, con vestuarios, duchas y zona de 
                        almacenamiento de material.
                        {% endblocktrans %}
                    </div>
                </div>
                <div class="col">
                    <div class="icon"><i class="fas fa-users fa-3x text-info"></i></div>
                    <div class="desc">
                        <h4>{% blocktrans %}Club de Socios{% endblocktrans %}</h4>
                        {% blocktrans %}
                        <b>Únete a nuestra comunidad</b> de surfistas. Disfruta de 
                        descuentos especiales, eventos exclusivos y alquiler de 
                        material con condiciones preferenciales.
                        {% endblocktrans %}
                    </div>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-md-6">
                    <h3>{% blocktrans %}Nuestra Ubicación{% endblocktrans %}</h3>
                    <p>
                        {% blocktrans %}
                        Situados en La Arena 21, Bajo 6, 48508 Zierbena, Bizkaia, 
                        estamos a solo 100 metros de una de las mejores playas para 
                        practicar surf en el País Vasco.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="col-md-6">
                    <h3>{% blocktrans %}Servicios{% endblocktrans %}</h3>
                    <ul class="list-unstyled">
                        <li><i class="fas fa-check text-success"></i> Cursos de surf</li>
                        <li><i class="fas fa-check text-success"></i> Alquiler de material</li>
                        <li><i class="fas fa-check text-success"></i> Campamentos de verano</li>
                        <li><i class="fas fa-check text-success"></i> Programas para centros educativos</li>
                        <li><i class="fas fa-check text-success"></i> Club de socios</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light py-5">
        <div class="container">
            <p class="see-more lead text-center">
                {% blocktrans %}
                Para más información visita 
                <a href="https://www.laarenasurfcenter.com/" target="_blank">laarenasurfcenter.com</a>
                o contáctanos en 
                <a href="mailto:centroyescueladesurflaarena@gmail.com">centroyescueladesurflaarena@gmail.com</a>
                {% endblocktrans %}
            </p>
        </div>
    </section>
</main>
{% endblock %}

arenasurf/templates/site_base.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}


{% block styles %}
    <link href="{% static "css/app.css" %}" rel="stylesheet" />
{% endblock %}


{% block extra_head_base %}
    <script defer src="https://use.fontawesome.com/releases/v6.5.0/js/all.js"></script>
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block topbar_base %}
<header>
    <div class="navbar {% block navbar_class %}navbar-expand-lg navbar-light bg-light{% endblock %}">
        <div class="container">
        {% block topbar %}
            {% block site_brand %}<a class="navbar-brand" href="{% url "home" %}">{{ SITE_NAME }}</a>{% endblock %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="fa fa-bars"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% block nav %}
                    <ul class="navbar-nav me-auto">
                        {% block nav_items %}
                        {% if user.is_authenticated and user.is_staff %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'bonos:dashboard' %}">
                                    <i class="fas fa-tachometer-alt"></i> Bonos
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'clientes:lista' %}">
                                    <i class="fas fa-users"></i> Clientes
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'socios:dashboard' %}">
                                    <i class="fas fa-user"></i> Socios
                                </a>
                            </li>
                        {% elif user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'clientes:panel' %}">
                                    <i class="fas fa-tachometer-alt"></i> Mi Panel
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'clientes:registro' %}">
                                    <i class="fas fa-user-plus"></i> Registro
                                </a>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated and user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="/admin/">
                                    <i class="fas fa-cogs"></i> Admin
                                </a>
                            </li>
                        {% endif %}
                        {% endblock %}
                    </ul>
                {% endblock %}
                {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
            </div>
        {% endblock %}
        </div>
    </div>
</header>
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    <script src="{% static "js/site.js" %}"></script>
{% endblock %}

{% block extra_body_base %}
    {% block extra_body %}{% endblock %}
{% endblock %}